#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

# Meshing
# runApplication blockMesh
# runApplication surfaceFeatures
# runApplication snappyHexMesh -overwrite
# extrudeMesh

# Clean run time folders
foamListTimes -rm
rm log.suzenPimple
rm -rf postProcessing

# Mapping fields
cp -a 0.org/. 0/
mapFields -sourceTime latestTime ../electricPotential

touch flowfield.foam

# Run the solver
# echo Solver running
# suzenSimple > log
runApplication $application

# postProcess -func singleGraph -latestTime
# python3 plots.py

echo
echo Case ended
